### ISSUE TITLE
Closing client socket with auto reconnect enabled

### ISSUE THREAD

**Issue by enbyted** [foreverjs/nssocket#33]
When closing client socket with 'reconnect' enabled using `socket.end()` scheduled reconnect function will crash the application (~line 322 in nssocket.js, when removing listeners from socket).
If I try `socket.destroy()` reconnect function would recreate the internal socket and connect to server, but it shouldn't, application requested closing of socket.

**Comment by genediazjr** [comment]
any chance you could provide us a snippet of the code?

**Comment by enbyted** [comment]
Currently I'm working on a big project with really short deadline, that's how I ran into it, but I'll make a test code when I'll get some time (probably in few days). Just a quickie how to reproduce:
- Create a nssocket with 'reconnect' option enabled and I believe it was type set to 'ipv4' (just like in example)
- Let it connect
- Call socket.end() - this will throw a exception after some time
OR - Call socket.destroy() - this will reopen the internal socket after some time

As I said earlier I'll write some code when I'll get some time, if it'll still be necessary.
I got around that issue by writing custom reconnect logic on application level.

**Comment by genediazjr** [comment]
Try putting an on 'error' handler like below

```javascript
socket.on('error', function (err) {
  log.error('client error', err);
});
```

**Comment by genediazjr** [comment]
@enbyted any updates? tnx!

**Comment by enbyted** [comment]
Thanks for the ping, I forgot about that in the mass of work lately, here is a failing test code:
```js
var net = require('net'),
    nssocket = require('nssocket');

net.createServer(function (socket) {
  console.log('client connected');
}).listen(8345);

var socket = new nssocket.NsSocket({
  reconnect: true,
  type: 'tcp4',
});

socket.on('start', function () {
  console.dir('start');
});

socket.on('error', function (err) {
  console.log('client error', err);
});

socket.connect(8345);
setTimeout(function() {
	socket.end();
}, 250);
```

So, that will crash with:
```
<workspace>/node_modules/nssocket/lib/nssocket.js:323                                                                                      
    self.socket.removeAllListeners();                                                                                                                      
                ^                                                                                                                                          
TypeError: Cannot call method 'removeAllListeners' of null                                                                                                 
    at doReconnect (<workspace>/node_modules/nssocket/lib/nssocket.js:323:17)                                                              
    at tryReconnect [as _onTimeout] (<workspace>/node_modules/nssocket/lib/nssocket.js:351:5)                                              
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)    
```

If you change the `socket.end()` to `socket.destroy()` it will not crash, but it'll reconnect _without_ calling on.start (you'll see on program's output one 'start' ond two 'client connected')

So, there is no way to close an autoreconnect socket.

Also, I'm using version '"0.5.3" from NPM repo, I think that's the newest.

**Comment by nucleardreamer** [comment]
+1 for merging this. @enbyted can you make a pull request?

**Comment by enbyted** [comment]
@nucleardreamer There already is one (https://github.com/foreverjs/nssocket/pull/34).

**Comment by nucleardreamer** [comment]
Oh awesome, thank you for writing that!
